title = "Gitleaks Configuration"

[extend]
useDefault = true

[allowlist]
description = "Allowed files and paths"
paths = [
    '''node_modules/''',
    '''dist/''',
    '''build/''',
    '''coverage/'''
]